CREATE TYPE "Role" AS ENUM ('ADMIN', 'OPERATOR', 'VISITOR');
CREATE TYPE "DemandStatus" AS ENUM ('OPEN', 'UNDER_ANALYSIS', 'WAITING_SUPPLIER', 'SIMULATION_READY', 'WAITING_APPROVAL', 'CONVERTED', 'CLOSED');
CREATE TYPE "ImportStatus" AS ENUM ('QUOTATION', 'APPROVAL', 'PAYMENT', 'PRODUCTION', 'SHIPMENT', 'IN_TRANSIT', 'PORT', 'CUSTOMS_CLEARANCE', 'INLAND_TRANSPORT', 'BANK_CLOSING', 'COMPLETED');
CREATE TYPE "DocumentType" AS ENUM ('PROFORMA', 'COMMERCIAL_INVOICE', 'BILL_OF_LADING', 'LICENSE', 'EXCHANGE_CONTRACT', 'PAYMENT_RECEIPT', 'CUSTOMS_DOCUMENT', 'OTHER');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'OVERDUE', 'CANCELLED');
CREATE TYPE "ApprovalDecision" AS ENUM ('APPROVED', 'REJECTED');
CREATE TYPE "AuditAction" AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'TRANSITION', 'UPLOAD', 'ACTIVATE', 'REOPEN');

CREATE TABLE "User" ("id" UUID PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'VISITOR', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Partner" ("id" UUID PRIMARY KEY, "legalName" TEXT NOT NULL, "tradeName" TEXT, "taxId" TEXT, "countryCode" TEXT, "email" TEXT, "phone" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Demand" ("id" UUID PRIMARY KEY, "code" TEXT NOT NULL UNIQUE, "title" TEXT NOT NULL, "description" TEXT, "status" "DemandStatus" NOT NULL DEFAULT 'OPEN', "requester" TEXT, "partnerId" UUID, "deletedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Quotation" ("id" UUID PRIMARY KEY, "demandId" UUID NOT NULL, "currency" CHAR(3) NOT NULL, "goodsValue" DECIMAL(18,4) NOT NULL, "estimatedLandedBrl" DECIMAL(18,2), "exchangeRate" DECIMAL(18,6), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Approval" ("id" UUID PRIMARY KEY, "quotationId" UUID NOT NULL, "decidedById" UUID NOT NULL, "decision" "ApprovalDecision" NOT NULL, "reason" TEXT, "decidedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ImportProcess" ("id" UUID PRIMARY KEY, "code" TEXT NOT NULL UNIQUE, "demandId" UUID NOT NULL UNIQUE, "partnerId" UUID NOT NULL, "status" "ImportStatus" NOT NULL DEFAULT 'QUOTATION', "originCountry" TEXT, "transportMode" TEXT, "destinationPort" TEXT, "eta" TIMESTAMP(3), "estimatedCostBrl" DECIMAL(18,2), "actualCostBrl" DECIMAL(18,2) NOT NULL DEFAULT 0, "bankClearedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "reopenedAt" TIMESTAMP(3), "reopenReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Document" ("id" UUID PRIMARY KEY, "importProcessId" UUID NOT NULL, "type" "DocumentType" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "DocumentVersion" ("id" UUID PRIMARY KEY, "documentId" UUID NOT NULL, "version" INTEGER NOT NULL, "objectKey" TEXT NOT NULL, "fileName" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" BIGINT NOT NULL, "checksum" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("documentId", "version"));
CREATE TABLE "Payment" ("id" UUID PRIMARY KEY, "importProcessId" UUID NOT NULL, "partnerId" UUID NOT NULL, "installment" INTEGER NOT NULL DEFAULT 1, "currency" CHAR(3) NOT NULL, "originalAmount" DECIMAL(18,4) NOT NULL, "estimatedBrl" DECIMAL(18,2), "paidBrl" DECIMAL(18,2), "dueDate" TIMESTAMP(3) NOT NULL, "paidAt" TIMESTAMP(3), "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Expense" ("id" UUID PRIMARY KEY, "importProcessId" UUID NOT NULL, "category" TEXT NOT NULL, "costCenter" TEXT NOT NULL, "description" TEXT NOT NULL, "amountBrl" DECIMAL(18,2) NOT NULL, "incurredAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Alert" ("id" UUID PRIMARY KEY, "importProcessId" UUID NOT NULL, "type" TEXT NOT NULL, "priority" INTEGER NOT NULL DEFAULT 1, "message" TEXT NOT NULL, "dueAt" TIMESTAMP(3), "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuditEvent" ("id" UUID PRIMARY KEY, "actorId" UUID, "action" "AuditAction" NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "before" JSONB, "after" JSONB, "reason" TEXT, "ipAddress" TEXT, "userAgent" TEXT, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "EntityVersion" ("id" UUID PRIMARY KEY, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "version" INTEGER NOT NULL, "snapshot" JSONB NOT NULL, "createdById" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("entityType", "entityId", "version"));

CREATE UNIQUE INDEX "DocumentVersion_one_active_per_document" ON "DocumentVersion" ("documentId") WHERE "active" = true;
CREATE INDEX "Demand_status_idx" ON "Demand"("status"); CREATE INDEX "ImportProcess_status_idx" ON "ImportProcess"("status"); CREATE INDEX "ImportProcess_eta_idx" ON "ImportProcess"("eta"); CREATE INDEX "Payment_status_dueDate_idx" ON "Payment"("status", "dueDate"); CREATE INDEX "AuditEvent_entity_idx" ON "AuditEvent"("entityType", "entityId", "occurredAt");

ALTER TABLE "Demand" ADD CONSTRAINT "Demand_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "Partner"("id") ON DELETE SET NULL;
ALTER TABLE "Quotation" ADD CONSTRAINT "Quotation_demandId_fkey" FOREIGN KEY ("demandId") REFERENCES "Demand"("id");
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_quotationId_fkey" FOREIGN KEY ("quotationId") REFERENCES "Quotation"("id"); ALTER TABLE "Approval" ADD CONSTRAINT "Approval_decidedById_fkey" FOREIGN KEY ("decidedById") REFERENCES "User"("id");
ALTER TABLE "ImportProcess" ADD CONSTRAINT "ImportProcess_demandId_fkey" FOREIGN KEY ("demandId") REFERENCES "Demand"("id"); ALTER TABLE "ImportProcess" ADD CONSTRAINT "ImportProcess_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "Partner"("id");
ALTER TABLE "Document" ADD CONSTRAINT "Document_importProcessId_fkey" FOREIGN KEY ("importProcessId") REFERENCES "ImportProcess"("id"); ALTER TABLE "DocumentVersion" ADD CONSTRAINT "DocumentVersion_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id");
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_importProcessId_fkey" FOREIGN KEY ("importProcessId") REFERENCES "ImportProcess"("id"); ALTER TABLE "Payment" ADD CONSTRAINT "Payment_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "Partner"("id");
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_importProcessId_fkey" FOREIGN KEY ("importProcessId") REFERENCES "ImportProcess"("id"); ALTER TABLE "Alert" ADD CONSTRAINT "Alert_importProcessId_fkey" FOREIGN KEY ("importProcessId") REFERENCES "ImportProcess"("id");
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL; ALTER TABLE "EntityVersion" ADD CONSTRAINT "EntityVersion_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id");
